### ISSUE TITLE
Not receiving battery charge notifications when connecting via Polar SDK to OH1

### ISSUE THREAD

**Issue by vanvalkenburg** [polarofficial/polar-ble-sdk#39]
When I connect to the OH1 from my Android app using the standard Battery Profile, I see notifications coming in for changes in the battery charge percentage (in multiples of 10), as expected.

However, if I use the Polar SDK, I get a callback to `batteryLevelReceived` upon connection, but never any update to the battery charge after that. HR and accelerometer data are received as expected.

**Comment by erkki-silvola** [comment]
current implementation is intended to work like that there is only once invoked callback of the battery level after connection, but I can change the implementation to invoke updates too as I can understand that there can be use cases for it...

**Comment by bhatramya** [comment]
Dear Polar team,

Is the implementation already changed to receive the battery level updates regularly? Please let me know when it is changed.

Thank you.

**Comment by erkki-silvola** [comment]
Hi,

It should work with the latest release

**Comment by bhatramya** [comment]
Thank you. It works! 👍

**Comment by vanvalkenburg** [comment]
This is working well now, thanks!

**Comment by vanvalkenburg** [comment]
There seems to be a regression on this as I can reproduce it on the latest version (v2.2.2).

Now that the code has been published (👍), I can see that the battery characteristic notifications are handled through a `Single` instead of `Flowable`.

**Comment by marmarelis** [comment]
Hello, I would be grateful for a fix to this as well.

**Comment by JOikarinen** [comment]
Bug shall be now fixed in [71cf6e8](https://github.com/polarofficial/polar-ble-sdk/commit/71cf6e85c65bea78968b55de1a672af8e6b56fcc). Originally fixed in 2.2.1 but was unfortunate reintroduced in release 2.2.2.

**Comment by marmarelis** [comment]
Thanks. From what I can tell, you updated the Android framework. If I am not mistaken, the bug still persists in the iOS version.

**Comment by JOikarinen** [comment]
@marmarelis filed new [issue](https://github.com/polarofficial/polar-ble-sdk/issues/130) to resolve the iOS-SDK too.

**Comment by JOikarinen** [comment]
Previous fix [71cf6e8](https://github.com/polarofficial/polar-ble-sdk/commit/71cf6e85c65bea78968b55de1a672af8e6b56fcc) introduced another regression bug. As BLE Battery Service client may get the battery status from BLE Battery Service before the any SDK client has started observing the changes  it is good to cache any received battery status. Fixed in [1ea946c](https://github.com/polarofficial/polar-ble-sdk/commit/1ea946c7297ca98579d9529b4910a5149c79117d)
